### ISSUE TITLE
linux.cc failing to compile in 1.11.1

### ISSUE THREAD

**Issue by nwflorek** [brndnmtthws/conky#708]
I'm seeing an issue when I try to compile release 1.11.1.

I'm using cmake version 3.13.2 on Linux Mint 18.3 Sylvia.

`cmake .. -DBUILD_OLD_CONFIG=ON -DBUILD_BUILTIN_CONFIG=ON -DCMAKE_INSTALL_PREFIX=/usr/local -DDEFAULTNETDEV=enp2s0`

```
[ 84%] Building CXX object src/CMakeFiles/conky.dir/linux.cc.o
/home/user/conky/src/linux.cc: In function ‘void update_gateway_info_failure(const char*)’:
/home/user/conky/src/linux.cc:305:20: error: missing template arguments before ‘lock’
   std::unique_lock lock(gw_info.mutex);
                    ^
/home/user/conky/src/linux.cc: In function ‘int update_gateway_info()’:
/home/user/conky/src/linux.cc:391:26: error: missing template arguments before ‘lock’
         std::unique_lock lock(gw_info.mutex);
                          ^
src/CMakeFiles/conky.dir/build.make:504: recipe for target 'src/CMakeFiles/conky.dir/linux.cc.o' failed
make[2]: *** [src/CMakeFiles/conky.dir/linux.cc.o] Error 1
CMakeFiles/Makefile2:259: recipe for target 'src/CMakeFiles/conky.dir/all' failed
make[1]: *** [src/CMakeFiles/conky.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by brndnmtthws** [comment]
What's your version of GCC?

**Comment by nwflorek** [comment]
I'm using gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11).

**Comment by brndnmtthws** [comment]
Thanks. I'll get a patch out later and make sure we're testing the builds against some older GCC versions.

**Comment by nwflorek** [comment]
Thanks a bunch!!
