### ISSUE TITLE
Build failure in 1.10.4 with -DBUILD_X11=OFF

### ISSUE THREAD

**Issue by Vincent-C** [brndnmtthws/conky#316]
Conky 1.10.4 fails to build when compiled with -DBUILD_X11=OFF (but builds ok with 1.10.3); this looks like a regression from changes made by @Ovnuniarchos in e2bd14e?

```
[ 23%] Building CXX object src/CMakeFiles/conky.dir/conky.cc.o
cd /build/conky-1.10.4/build-cli/src && /usr/bin/c++   -D_LARGEFILE64_SOURCE -D_POSIX_C_SOURCE=200809L -I/build/conky-1.10.4/build-cli -I/usr/include/lua5.1 -I/build/conky-1.10.4/build-cli/data  -std=c++0x -g -O2 -fdebug-prefix-map=/build/conky-1.10.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -o CMakeFiles/conky.dir/conky.cc.o -c /build/conky-1.10.4/src/conky.cc
/build/conky-1.10.4/src/conky.cc: In function 'int draw_each_line_inner(char*, int, int)':
/build/conky-1.10.4/src/conky.cc:1814:7: error: 'cur_x' was not declared in this scope
       cur_x = (int) current->arg;
       ^~~~~
/build/conky-1.10.4/src/conky.cc: In function 'void draw_stuff()':
/build/conky-1.10.4/src/conky.cc:1937:2: error: 'text_offset_x' was not declared in this scope
  text_offset_x = text_offset_y = 0;
  ^~~~~~~~~~~~~
/build/conky-1.10.4/src/conky.cc:1937:18: error: 'text_offset_y' was not declared in this scope
  text_offset_x = text_offset_y = 0;
                  ^~~~~~~~~~~~~
src/CMakeFiles/conky.dir/build.make:161: recipe for target 'src/CMakeFiles/conky.dir/conky.cc.o' failed
make[4]: *** [src/CMakeFiles/conky.dir/conky.cc.o] Error 1
```

**Comment by Vincent-C** [comment]
This would be fixed by PR #317
