### ISSUE TITLE
Conky 1.10.1 undefined references

### ISSUE THREAD

**Issue by widgeteye** [brndnmtthws/conky#193]
I tried to build with lua 5.1 and when it got to that section of the build it got the error ;
CMakeFiles/conky.dir/lua-config.cc.o: In function `lua::state::newtable()':
/usr/local/src/conky-1.10.1/src/luamm.hh:244: undefined reference to`lua_createtable'

Tons of 'em, so I uninstalled lua and searched all the /lib and /include directories for anything stray and removed it, then made a clean install of lua 5.3.2,  emptied the conky/build directory and started over and got the same errors and the build died. Any help?
Thanks

**Comment by marcpayne** [comment]
Are you trying to build with any of the lua bindings, like cairo, imlib2, or rsvg? I committed a change to my own repo to force conky to compile against lua 5.1 in this case. Currently, 1.10.1 will pull in lua 5.2 or greater, regardless of whether you have lua 5.1 installed.

If I'm right about the problem, feel free to apply commit 0dbd27d2de2 and see if it helps. You'll need to reinstall lua 5.1 (you can keep lua 5.3.2 if you want).

I hope this helps!

**Comment by widgeteye** [comment]
On Wed, 30 Dec 2015 12:56:03 -0800
marcpayne <notifications@github.com> wrote:

heh, I've tried building the lua binding for cairo but there seems to
be no web site anymore. I do have imlib2 installed already and cairo
but after installing all LUA's from 5.1 to 5.3, I can't get conky to
build with anything even the older conky 1.9.  And it's always the same
error no matter which version of lua I try. I have even built a lua.pc
with each of the new versions of lua I install. I've tried setting the
FLAGS for everything I've built to no avail. I've been at this now
for over 8 hours. And I am a 20 year Slackware user, I am stumped.
And Now I'm about three sheets to the wind and I'm having to keep
correcting spelling errors because my hands are drunk too.  :)

Think I'll give up for the evening, <-HA, try to type that when your
crocked. 

Thanks for quickly replying to my note on the site. I am seriously
considering switching to Arch linux, only because it has a really good
package manager with excellent dependency (shit, excellent dependency
what? Lemme think a minute I know that word's in my vocabulary.) AH!
resolution was the word I was looking for. Anyway, at 66 years old I am
getting a little long in the tooth to be setting up all night in
dependency HELLLL!  LOL

Good night and thanks again, Marcpayne. Maybe I'll talk to you
again later. Think I'll go have another beer. I make my own and DAMN,
it's good!   LOL

Larry

**Comment by marcpayne** [comment]
Switching to Arch (from Slackware) was the best distro hop I ever made, and the last. Slackware was fun and a very good distro, but I reached a point where I needed to get actual non-Linux work done on a daily basis. It is so nice to run `pacman -S whatever` and get the latest version of "whatever" immediately with well-chosen dependencies. I check the mailing list and front page daily, and my system is rock-solid. If you switch, have a copy of the beginner's guide nearby. It helps, even for an experienced user.

Back on topic, I'd forgotten that there are two separate lua issues going on that I'm aware of. You've probably already seen them, but here they are anyway: #174 and #116. Maybe you'll get some useful info. My knowledge is still limited, so I probably can't help much more for now.

**Comment by plikhari** [comment]
@marcpayne 
Well I am on Arch since 2007 ~ 2008 - went from Win boxes to Ubuntu [ Linux break in time ;-)) ] on to Arch. Fantabulous !!! There are so many who are making the switch to Arch. Some of the responses I get are about the speed and simplicity and of course the magic with pacman. 
#116 - lua53 is a long shot - time is perhaps the main challenge for everyone - intent I am sure is plenty...

@widgeteye 
You're still a young lad - horses and men - you know :-)) ... Perhaps switching to Arch will indeed save some sanity - just had 2 guys in their 70s and 1 your sprightly young age switch around huahahahaha. I am sure you have read this some where ```40 is the old age of youth - while 50 is the youth of old age``` 

On Arch I am now able to build without the ```LDFLAGS and LUA_CFLAGS``` but I still leave them there.
```
	LDFLAGS="-llua5.1 -lm"
	LUA_CFLAGS="-I/usr/include/lua5.1"

	cmake \
		-D CMAKE_C_FLAGS="${LUA_CFLAGS}" \
		-D CMAKE_CXX_FLAGS="${LUA_CFLAGS}" \
		-D CMAKE_EXE_LINKER_FLAGS="${LDFLAGS}" \
		...other options go here
		.
	make
```
If you adjust and add this to the slackbuild file - you should be good to go.

Have a Fantastic New Year :-))

**Comment by widgeteye** [comment]
Thanks for your reply,I'm in the middle of installing arch right now and have use the phone for email. Not too concerned about Lua and coney at this point. Lol I'll get back to you as soon as I have real mail. :)



Sent via the Samsung GALAXY S® 5, an AT&T 4G LTE smartphone

-------- Original message --------

**Comment by lasers** [comment]
2 years 7 months passed. You must be 69 years old now... and still drunk, I suspect. ;-)
Anyway, here on my Arch machine, I was able to cmake `conky` okay with all `BUILD_LUA_*` flags.
```
-DBUILD_LUA_CAIRO=ON \
-DBUILD_LUA_IMLIB2=ON \
-DBUILD_LUA_RSVG=ON \
-DBUILD_LUA_CAIRO=ON \
-DBUILD_LUA_CAIRO=ON \
-DBUILD_LUA_IMLIB2=ON \
-DBUILD_LUA_RSVG=ON \
-DBUILD_LUA_CAIRO=ON \
```

Here's a Changelog for the two `luamm.*` files since this issue was opened.
```
* 3 months ago 4b92556f Brenden Matthews Build improvements: clang-tidy, sonar, Dockerfile. (#488)
* 3 months ago eebc8c65 Brenden Matthews Add formatting/static analysis (#486)
* 3 months ago b20d83b7 npyl Basic macOS support (#480)
* 8 months ago c93a007a albert2004 Fix gcc-7 compilation error. (#402)
* 1 year, 10 months ago 3a006806 Guido Falsi FreeBSD changes (#327)
```

First, we have a `DockerFile` now and it does have the same flags above.
Second, it's possible that this issue is unrelated to `conky` and more to do with `Slackware`... is which why you switched over to `Arch` approximately 2 years and 7 months ago.
Third, the most recent commit `eebc8c65` contains lot of build fixes. It touched `lua` files too.

It looks like the `lua` build issues might be ironed out already by *Owner* or other contributors so it is probably working okay now. Please chime in if it's still broken. Thanks. Closing this
